server.port=8080

# ===== ????????? KAFKA (KRaft mode - ??? ??? ??, ?????? ????????? ??????) =====
spring.kafka.bootstrap-servers=localhost:9092

# === ????????? ????????? ===
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.properties.spring.json.type.mapping=joke:com.example.jokekafkaproducer.model.Joke

# Producer ?????????
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# === ???????? ???????? ===
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.request.timeout.ms=30000

# ===== WebClient =====
spring.codec.max-in-memory-size=2MB

# ===== ??????????? =====
logging.level.com.example.jokekafkaproducer=DEBUG
logging.level.org.apache.kafka.clients.producer=INFO

# ?????! ???????? ??? ?????????:
spring.kafka.producer.properties.spring.json.type.mapping=joke:com.example.jokekafkaproducer.model.Joke
spring.kafka.producer.properties.spring.json.trusted.packages=*

# ? application.properties
joke.scheduler.fixed-rate=10000


